### ISSUE TITLE
Import from Silence

### ISSUE THREAD

**Issue by Pommede** [dekusms/DekuSMS-Android#158]
Hi everybody
i'd like to test this very promising app but i had silence and i want to import all my sms in deku
is there a way to do that ?
i can export my silence sms unencrypted in SilencePlaintextBackup.xml... and after ? (silence uses a special directory..not the usually one)
Thks

**Comment by Geo25rey** [comment]
It's my understanding that Silence supported more than just text, such as images or videos. If that is expected to be included with this feature, I'd say this is blocked by #148 (MMS support)

**Comment by DubbaThony** [comment]
If anyone stumbles uppon this issue before it's implemented, there is workaround: silence allows exporting plaintext, which is compatible with sms backup & restore app, which you can use to restore sms into system text messages provider. Than you can have your Silence messages in Deku.

Just make sure to clean up the backup file from your storage, you don't want random app to be reading your texts :)
