### ISSUE TITLE
Not functioning on Vivo phone

### ISSUE THREAD

**Issue by atulraj85** [dekusms/DekuSMS-Android#265]
![1725931191898](https://github.com/user-attachments/assets/39fc126e-e91e-4137-b097-f045331e8f05)

I tried sending message from my other mobile phone to this Vivo phone, the app is working correctly.
1. UI is a bit different.
    1. Navigation buttons weren't visible.
    2. Top app bar color was weird.
2. When sending Secure Conversation request from other phone to this phone, the App crashed. So could not connect any further.

**Comment by sherlockwisdom** [comment]
thank you for the screenshots, please if you can attach how it looks on your device it will be helpful - please blur out any sensitive information that shouldn't be shared. You can also send to developers@dekusms.com

Please try secure conversation with the new release coming out - there's been some major upgrades
