### ISSUE TITLE
Cannot get past "Set default SMS app" screen on 0.48.0.

### ISSUE THREAD

**Issue by Arson31** [dekusms/DekuSMS-Android#268]
Using Pixel 9 Graphene OS ROM.

**Comment by sherlockwisdom** [comment]
Are you on Android 15?

**Comment by Arson31** [comment]
Yes

**Comment by DubbaThony** [comment]
IDK if it's helpful, but can repro on crDroid on Android 15.

And Im convinced Android changed something up with Android 15, since Silence (other sms app I used to use) doesn't work well either. Finally got it to work but notifications don't work at all, and the app thinks its not default.

**Comment by sherlockwisdom** [comment]
The latest version should fix this issue - you are correct there has been come changes in Android 15 that breaks how default SMS apps are recognized
